### ISSUE TITLE
请问如何使用它们？

### ISSUE THREAD

**Issue by anlongstory** [CSshengxy/MEC#1]
如题，这里只有.cpp 是只实现了 CPU 上加速没有 GPU 上的加速吗？

**Comment by CSshengxy** [comment]
是的，没有涉及到GPU.

**Comment by CSshengxy** [comment]
程序运行方法在README中更新了，希望对你有所帮助。

**Comment by anlongstory** [comment]
谢谢，最近想做一下加速 caffe 的 forward，看到了这篇论文。
